name: Build multi-arch Docker Image

on:
  release:
    types: [published]
  push:
    branches:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Setup for buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      if: ${{ matrix.os != "windows-latest" }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      if: ${{ matrix.os != "windows-latest" }}

    # Debugging information
    - name: Docker info
      run: docker info
      if: ${{ matrix.os != "windows-latest" }}
    - name: Buildx inspect
      run: docker buildx inspect
      if: ${{ matrix.os != "windows-latest" }}

    # Build and (optionally) push the image
    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        # Only push if we are publishing a release
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        # Use a 'temp' tag, that won't be pushed, for non-release builds
        tags: testcontainers/ryuk:${{ github.event.release.tag_name || 'temp' }}
